export const GET_ALL_COMMODITY = 'GET_ALL_COMMODITY';
export const GET_COMMODITY = 'GET_COMMODITY';
export const CREATE_COMMODITY = 'CREATE_COMMODITY';
export const UPDATE_COMMODITY = 'UPDATE_COMMODITY';
export const UPDATE_UNIT = 'UPDATE_UNIT';
export const CLEAR_COMMODITY = 'CLEAR_COMMODITY';
export const COMMODITY_ERROR = 'COMMODITY_ERROR';
export const SET_CURRENT = 'SET_CURRENT';
